#!/bin/bash

#SBATCH --job-name d2q9-openmp
#SBATCH -N1
#SBATCH --gres=gpu:1
#SBATCH --time 00:35:00
#SBATCH --partition gpu_veryshort
#SBATCH --output out_d2q9GPU.out


echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

echo ------- 128x128 --------------
#! Run the executable
./d2q9-bgk input_128x128.params obstacles_128x128.dat
echo -----------------------------

echo -------- 128x256 -------------
./d2q9-bgk input_128x256.params obstacles_128x256.dat
echo ------------------------------

echo --------- 256x256 -----------
./d2q9-bgk input_256x256.params obstacles_256x256.dat
echo -----------------------------

echo -------- 1024x1024-----------
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
echo ------------------------------
