#!/bin/bash

#SBATCH --job-name d2q9-openmp
#SBATCH -N1
#SBATCH --gres=gpu:1
#SBATCH --time 00:15:00
#SBATCH --partition gpu
#SBATCH --output out_d2q9GPU.out


echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
./d2q9-bgk input_128x128.params obstacles_128x128.dat
