#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --partition cpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --time=0:20:15
#SBATCH --output TestingMultipleSizesN1T20.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
echo icc
echo NUMBER OF NODES : $SLURM_NNODES
echo CPUS per node : $SLURM_JOB_CPUS_PER_NODE

echo --------- Size : 128 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_128x128.params obstacles_128x128.dat
echo ----------------------------------
echo
echo
echo

echo ---------- Size : 256 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_256x256.params obstacles_256x256.dat
echo ----------------------------------
echo
echo
echo

echo --------- Size : 1024 ------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
echo ----------------------------------
echo
echo
echo

echo done!
