#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --partition serial
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --time=1:25:15
#SBATCH --output TimingTestsN2T1.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
echo icc
echo NUMBER OF NODES : $SLURM_NNODES
echo CPUS per node : $SLURM_JOB_CPUS_PER_NODE

echo --------- Size : 128x128 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_128x128.params obstacles_128x128.dat
echo done!

echo --------- Size : 128x256 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_128x256.params obstacles_128x256.dat
echo done!

echo --------- Size : 256x256 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_256x256.params obstacles_256x256.dat
echo done!


echo --------- Size : 1024x1024 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
echo done!
