#!/bin/bash
#SBATCH --job-name d2q9-bgk
#SBATCH --partition serial
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=14
#SBATCH --time=1:25:15
#SBATCH --output TimingTestsN2T24NO.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
echo icc
echo NUMBER OF NODES : $SLURM_NNODES
echo CPUS per node : $SLURM_JOB_CPUS_PER_NODE

echo --------- Size : 128x128 --------------
mpirun -np $SLURM_JOB_CPUS_PER_NODE ./d2q9-bgk input_128x128.params obstacles_128x128.dat
echo done!
